name: Deploy to Kubernetes (K3s)

on:
  push:
    branches: [ "main" ]

jobs:
  # FASE 1: Verificación de salud
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Verificar construcción de Docker
        run: docker build -t talcatravel-test .

  # FASE 2: Despliegue en Kubernetes
  deploy:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Autenticación en Docker Hub
        uses: docker/login-action@v3
        with:
          username: elifokami
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compilación y Push de la Imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          no-cache: true
          tags: elifokami/talcatravel-backend:latest
      
      - name: Copiar carpeta k8s a AWS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          source: "k8s/*"
          target: "/home/ubuntu/talcatravel-deploy"

      - name: Despliegue en AWS (Kubernetes Rollout)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            # 1. Aplicar todos los archivos YAML que subimos a la carpeta k8s
            sudo kubectl apply -f /home/ubuntu/talcatravel-deploy/k8s/

            sudo kubectl rollout restart deployment/talcatravel-backend